version: '3.8'

services:
  ipa-server:
    image: freeipa/freeipa-server:centos-8-4.8.7
    container_name: ipa-server
    hostname: ipa.example.com
    ports:
      - "80:80"
      - "443:443"
      - "389:389"
      - "636:636"
      - "88:88"
      - "464:464"
      - "88:88/udp"
      - "464:464/udp"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      -a-data:/data:Z
    environment:
      - PASSWORD=YOUR_PASSWORD
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    command: ipa-server-install -U -r example.com --no-ntp

volumes:
  ipa-data:
